"""Default mapping metadata for all ebusd registers."""

from __future__ import annotations

from .models import RegisterMeta

REGISTER_MAP: dict[str, RegisterMeta] = {
    # hmu (Heat Pump)
    "hmu.Status01": RegisterMeta(
        friendly_name="Status",
        icon="mdi:information",
        entity_category="diagnostic",
    ),
    "hmu.StatusCirPump": RegisterMeta(
        friendly_name="Circulation Pump",
        entity_type="binary_sensor",
        entity_category="diagnostic",
    ),
    "hmu.Currenterror": RegisterMeta(
        friendly_name="Error",
        icon="mdi:alert",
        entity_category="diagnostic",
    ),
    "hmu.FlowTemp": RegisterMeta(
        friendly_name="Flow Temperature",
        device_class="temperature",
        unit="°C",
    ),
    "hmu.FlowTemperature": RegisterMeta(
        friendly_name="Flow Temperature (alt)",
        device_class="temperature",
        unit="°C",
    ),
    "hmu.RunDataCompressorSpeed": RegisterMeta(
        friendly_name="Compressor Speed",
        icon="mdi:speedometer",
        unit="rpm",
    ),
    "hmu.RunDataHighPressure": RegisterMeta(
        friendly_name="High Pressure",
        device_class="pressure",
        unit="bar",
    ),
    "hmu.RunDataLowPressure": RegisterMeta(
        friendly_name="Low Pressure",
        device_class="pressure",
        unit="bar",
        enabled=False,
    ),
    "hmu.RunDataCompressorInletTemp": RegisterMeta(
        friendly_name="Compressor Inlet Temperature",
        device_class="temperature",
        unit="°C",
    ),
    "hmu.RunDataCompressorOutletTemp": RegisterMeta(
        friendly_name="Compressor Outlet Temperature",
        device_class="temperature",
        unit="°C",
    ),
    "hmu.RunDataEEVOutletTemp": RegisterMeta(
        friendly_name="EEV Outlet Temperature",
        device_class="temperature",
        unit="°C",
    ),
    "hmu.RunDataEEVPositionAbs": RegisterMeta(
        friendly_name="EEV Position",
        icon="mdi:valve",
        unit="%",
    ),
    "hmu.RunDataFan1Speed": RegisterMeta(
        friendly_name="Fan 1 Speed",
        icon="mdi:fan",
        unit="rpm",
    ),
    "hmu.RunDataFan2Speed": RegisterMeta(
        friendly_name="Fan 2 Speed",
        icon="mdi:fan",
        unit="rpm",
    ),
    "hmu.RunDataStatuscode": RegisterMeta(
        friendly_name="Compressor Status",
        icon="mdi:information",
    ),
    "hmu.RunDataAirInletTemp": RegisterMeta(
        friendly_name="Air Inlet Temperature",
        device_class="temperature",
        unit="°C",
    ),
    "hmu.RunDataBuildingCPumpPower": RegisterMeta(
        friendly_name="Building Circulation Pump Speed",
        icon="mdi:percent",
        unit="%",
    ),
    "hmu.CurrentConsumedPower": RegisterMeta(
        friendly_name="Compressor Power",
        device_class="power",
        unit="kW",
    ),
    "hmu.CurrentYieldPower": RegisterMeta(
        friendly_name="Thermal Output",
        device_class="power",
        unit="kW",
    ),
    "hmu.CurrentCompressorUtil": RegisterMeta(
        friendly_name="Compressor Utilisation",
        icon="mdi:percent",
        unit="%",
    ),
    "hmu.SupplyTempWeighted": RegisterMeta(
        friendly_name="Supply Temperature (weighted)",
        device_class="temperature",
        unit="°C",
    ),
    "hmu.TotalEnergyUsage": RegisterMeta(
        friendly_name="Total Energy",
        device_class="energy",
        unit="kWh",
        state_class="total_increasing",
    ),
    "hmu.CopHc": RegisterMeta(
        friendly_name="COP Heating",
        icon="mdi:lightning-bolt",
    ),
    "hmu.CopHwc": RegisterMeta(
        friendly_name="COP DHW",
        icon="mdi:lightning-bolt",
    ),
    "hmu.CopCooling": RegisterMeta(
        friendly_name="COP Cooling",
        icon="mdi:lightning-bolt",
    ),
    "hmu.YieldHc": RegisterMeta(
        friendly_name="Yield Heating",
        device_class="energy",
        unit="kWh",
        state_class="total_increasing",
    ),
    "hmu.YieldHcDay": RegisterMeta(
        friendly_name="Yield Heating Today",
        device_class="energy",
        unit="kWh",
    ),
    "hmu.YieldHwc": RegisterMeta(
        friendly_name="Yield DHW",
        device_class="energy",
        unit="kWh",
        state_class="total_increasing",
    ),
    "hmu.YieldCoolDay": RegisterMeta(
        friendly_name="Yield Cooling Today",
        device_class="energy",
        unit="kWh",
    ),
    "hmu.RunStatsCompressorHours": RegisterMeta(
        friendly_name="Compressor Runtime",
        device_class="duration",
        unit="h",
        state_class="total_increasing",
        entity_category="diagnostic",
        entity_type="sensor",
    ),
    "hmu.RunStatsCompressorStarts": RegisterMeta(
        friendly_name="Compressor Starts",
        icon="mdi:counter",
        state_class="total_increasing",
        entity_category="diagnostic",
        entity_type="sensor",
    ),
    "hmu.RunStatsFan1Hours": RegisterMeta(
        friendly_name="Fan 1 Runtime",
        device_class="duration",
        unit="h",
        state_class="total_increasing",
        entity_category="diagnostic",
        entity_type="sensor",
    ),
    "hmu.RunStatsFan2Hours": RegisterMeta(
        friendly_name="Fan 2 Runtime",
        device_class="duration",
        unit="h",
        state_class="total_increasing",
        entity_category="diagnostic",
        entity_type="sensor",
    ),
    "hmu.RunStatsBuildingCPumpStarts": RegisterMeta(
        friendly_name="Building Pump Starts",
        icon="mdi:counter",
        state_class="total_increasing",
        entity_category="diagnostic",
        entity_type="sensor",
    ),
    "hmu.RunStatsBuildingPumpHours": RegisterMeta(
        friendly_name="Building Pump Runtime",
        device_class="duration",
        unit="h",
        state_class="total_increasing",
        entity_category="diagnostic",
        entity_type="sensor",
    ),
    "hmu.RunStatsFan1Starts": RegisterMeta(
        friendly_name="Fan 1 Starts",
        icon="mdi:counter",
        state_class="total_increasing",
        entity_category="diagnostic",
        entity_type="sensor",
    ),
    "hmu.RunStatsFan2Starts": RegisterMeta(
        friendly_name="Fan 2 Starts",
        icon="mdi:counter",
        state_class="total_increasing",
        entity_category="diagnostic",
        entity_type="sensor",
    ),
    "hmu.RunStatsHcHours": RegisterMeta(
        friendly_name="Heating Runtime",
        device_class="duration",
        unit="h",
        state_class="total_increasing",
        entity_category="diagnostic",
        entity_type="sensor",
    ),
    "hmu.RunStatsHMUHours": RegisterMeta(
        friendly_name="HMU Runtime",
        device_class="duration",
        unit="h",
        state_class="total_increasing",
        entity_category="diagnostic",
        entity_type="sensor",
    ),
    "hmu.RunStatsHwcHours": RegisterMeta(
        friendly_name="DHW Runtime",
        device_class="duration",
        unit="h",
        state_class="total_increasing",
        entity_category="diagnostic",
        entity_type="sensor",
    ),
    "hmu.RunStats4PortValveHours": RegisterMeta(
        friendly_name="4-Port Valve Runtime",
        device_class="duration",
        unit="h",
        state_class="total_increasing",
        entity_category="diagnostic",
        entity_type="sensor",
    ),
    "hmu.RunStats4PortValveSwitches": RegisterMeta(
        friendly_name="4-Port Valve Switches",
        icon="mdi:counter",
        state_class="total_increasing",
        entity_category="diagnostic",
        entity_type="sensor",
    ),
    "hmu.PowerConsumptionHmu": RegisterMeta(
        friendly_name="Power Consumption (HMU)",
        device_class="energy",
        unit="kWh",
        state_class="total_increasing",
    ),
    "hmu.BuildingCircuitFlow": RegisterMeta(
        friendly_name="Building Circuit Flow",
        icon="mdi:water",
        unit="l/min",
        entity_type="sensor",
    ),
    "hmu.DateTime": RegisterMeta(
        friendly_name="Date/Time",
        icon="mdi:clock",
        entity_category="diagnostic",
    ),
    # ctlv2 (Heating Control)
    "ctlv2.Hc1ActualFlowTempDesired": RegisterMeta(
        friendly_name="Flow Temperature Target (HC1)",
        device_class="temperature",
        unit="°C",
        writable=True,
        min_value=5,
        max_value=75,
        step=0.5,
        entity_type="number",
        entity_category="config",
    ),
    "ctlv2.Hc1PumpStatus": RegisterMeta(
        friendly_name="Pump Status (HC1)",
        entity_type="binary_sensor",
    ),
    "ctlv2.Z1ActualRoomTempDesired": RegisterMeta(
        friendly_name="Room Temperature Target (Z1)",
        device_class="temperature",
        unit="°C",
        writable=True,
        min_value=5,
        max_value=30,
        step=0.5,
        entity_type="number",
        entity_category="config",
    ),
    "ctlv2.Z1DayTemp": RegisterMeta(
        friendly_name="Day Temperature (Z1)",
        device_class="temperature",
        unit="°C",
        writable=True,
        min_value=5,
        max_value=30,
        step=0.5,
        entity_type="number",
        entity_category="config",
    ),
    "ctlv2.Z1NightTemp": RegisterMeta(
        friendly_name="Night Temperature (Z1)",
        device_class="temperature",
        unit="°C",
        writable=True,
        min_value=5,
        max_value=30,
        step=0.5,
        entity_type="number",
        entity_category="config",
    ),
    "ctlv2.Z1OpMode": RegisterMeta(
        friendly_name="Operation Mode (Z1)",
        writable=True,
        options=["day", "night", "auto", "off"],
        entity_type="select",
        entity_category="config",
    ),
    "ctlv2.Hc1FlowTemp": RegisterMeta(
        friendly_name="Flow Temperature (HC1)",
        device_class="temperature",
        unit="°C",
    ),
    "ctlv2.Hc1HeatCurve": RegisterMeta(
        friendly_name="Heat Curve (HC1)",
        writable=True,
        min_value=0.1,
        max_value=4.0,
        step=0.05,
        entity_type="number",
        entity_category="config",
    ),
    "ctlv2.Hc1MaxFlowTempDesired": RegisterMeta(
        friendly_name="Max Flow Temperature (HC1)",
        device_class="temperature",
        unit="°C",
        writable=True,
        min_value=20,
        max_value=75,
        step=1,
        entity_type="number",
        entity_category="config",
    ),
    "ctlv2.Hc1MinFlowTempDesired": RegisterMeta(
        friendly_name="Min Flow Temperature (HC1)",
        device_class="temperature",
        unit="°C",
        writable=True,
        min_value=5,
        max_value=40,
        step=1,
        entity_type="number",
        entity_category="config",
    ),
    "ctlv2.Hc1SummerTempLimit": RegisterMeta(
        friendly_name="Summer Temp Limit (HC1)",
        device_class="temperature",
        unit="°C",
        writable=True,
        min_value=10,
        max_value=30,
        step=1,
        entity_type="number",
        entity_category="config",
    ),
    "ctlv2.Hc1MinCoolingTempDesired": RegisterMeta(
        friendly_name="Min Cooling Temp (HC1)",
        device_class="temperature",
        unit="°C",
        writable=True,
        min_value=5,
        max_value=30,
        step=1,
        entity_type="number",
        entity_category="config",
    ),
    "ctlv2.Hc1AutoOffMode": RegisterMeta(
        friendly_name="Auto Off Mode (HC1)",
        icon="mdi:thermostat-auto",
        writable=True,
        options=["eco", "comfort"],
        entity_type="select",
        entity_category="config",
    ),
    "ctlv2.Hc1RoomTempSwitchOn": RegisterMeta(
        friendly_name="Room Temp Threshold (HC1)",
        unit="°C",
    ),
    "ctlv2.Hc1Status": RegisterMeta(
        friendly_name="Status (HC1)",
        entity_type="sensor",
        icon="mdi:information",
    ),
    "ctlv2.Hc1CircuitType": RegisterMeta(
        friendly_name="Circuit Type (HC1)",
        icon="mdi:information",
        entity_category="diagnostic",
    ),
    "ctlv2.Hc1ExcessTemp": RegisterMeta(
        friendly_name="Excess Temp (HC1)",
        device_class="temperature",
        unit="°C",
    ),
    "ctlv2.Hc1HeatCurveAdaption": RegisterMeta(
        friendly_name="Heat Curve Adaption (HC1)",
        icon="mdi:chart-bell-curve-cumulative",
    ),
    "ctlv2.Hc1MixerMovement": RegisterMeta(
        friendly_name="Mixer Movement (HC1)",
        icon="mdi:valve",
    ),
    # HC2
    "ctlv2.Hc2ActualFlowTempDesired": RegisterMeta(
        friendly_name="Flow Temperature Target (HC2)",
        device_class="temperature",
        unit="°C",
        writable=True,
        min_value=5,
        max_value=75,
        step=0.5,
        entity_type="number",
        entity_category="config",
    ),
    "ctlv2.Hc2FlowTemp": RegisterMeta(
        friendly_name="Flow Temperature (HC2)",
        device_class="temperature",
        unit="°C",
    ),
    "ctlv2.Hc2HeatCurve": RegisterMeta(
        friendly_name="Heat Curve (HC2)",
        writable=True,
        min_value=0.1,
        max_value=4.0,
        step=0.05,
        entity_type="number",
        entity_category="config",
    ),
    "ctlv2.Hc2MaxFlowTempDesired": RegisterMeta(
        friendly_name="Max Flow Temperature (HC2)",
        device_class="temperature",
        unit="°C",
        writable=True,
        min_value=20,
        max_value=75,
        step=1,
        entity_type="number",
        entity_category="config",
    ),
    "ctlv2.Hc2MinFlowTempDesired": RegisterMeta(
        friendly_name="Min Flow Temperature (HC2)",
        device_class="temperature",
        unit="°C",
        writable=True,
        min_value=5,
        max_value=40,
        step=1,
        entity_type="number",
        entity_category="config",
    ),
    "ctlv2.Hc2SummerTempLimit": RegisterMeta(
        friendly_name="Summer Temp Limit (HC2)",
        device_class="temperature",
        unit="°C",
        writable=True,
        min_value=10,
        max_value=30,
        step=1,
        entity_type="number",
        entity_category="config",
    ),
    "ctlv2.Hc2MinCoolingTempDesired": RegisterMeta(
        friendly_name="Min Cooling Temp (HC2)",
        device_class="temperature",
        unit="°C",
        writable=True,
        min_value=5,
        max_value=30,
        step=1,
        entity_type="number",
        entity_category="config",
    ),
    "ctlv2.Hc2AutoOffMode": RegisterMeta(
        friendly_name="Auto Off Mode (HC2)",
        icon="mdi:thermostat-auto",
        writable=True,
        options=["eco", "comfort"],
        entity_type="select",
        entity_category="config",
    ),
    "ctlv2.Hc2PumpStatus": RegisterMeta(
        friendly_name="Pump Status (HC2)",
        entity_type="binary_sensor",
    ),
    "ctlv2.Hc2Status": RegisterMeta(
        friendly_name="Status (HC2)",
        entity_type="sensor",
        icon="mdi:information",
    ),
    "ctlv2.Hc2CircuitType": RegisterMeta(
        friendly_name="Circuit Type (HC2)",
        icon="mdi:information",
        entity_category="diagnostic",
    ),
    "ctlv2.Hc2ExcessTemp": RegisterMeta(
        friendly_name="Excess Temp (HC2)",
        device_class="temperature",
        unit="°C",
    ),
    "ctlv2.Hc2HeatCurveAdaption": RegisterMeta(
        friendly_name="Heat Curve Adaption (HC2)",
        icon="mdi:chart-bell-curve-cumulative",
    ),
    "ctlv2.Hc2RoomTempSwitchOn": RegisterMeta(
        friendly_name="Room Temp Threshold (HC2)",
        unit="°C",
    ),
    "ctlv2.Hc2MixerMovement": RegisterMeta(
        friendly_name="Mixer Movement (HC2)",
        icon="mdi:valve",
    ),
    # HC3
    "ctlv2.Hc3ActualFlowTempDesired": RegisterMeta(
        friendly_name="Flow Temperature Target (HC3)",
        device_class="temperature",
        unit="°C",
        writable=True,
        min_value=5,
        max_value=75,
        step=0.5,
        entity_type="number",
        entity_category="config",
    ),
    "ctlv2.Hc3FlowTemp": RegisterMeta(
        friendly_name="Flow Temperature (HC3)",
        device_class="temperature",
        unit="°C",
    ),
    "ctlv2.Hc3HeatCurve": RegisterMeta(
        friendly_name="Heat Curve (HC3)",
        writable=True,
        min_value=0.1,
        max_value=4.0,
        step=0.05,
        entity_type="number",
        entity_category="config",
    ),
    "ctlv2.Hc3MaxFlowTempDesired": RegisterMeta(
        friendly_name="Max Flow Temperature (HC3)",
        device_class="temperature",
        unit="°C",
        writable=True,
        min_value=20,
        max_value=75,
        step=1,
        entity_type="number",
        entity_category="config",
    ),
    "ctlv2.Hc3MinFlowTempDesired": RegisterMeta(
        friendly_name="Min Flow Temperature (HC3)",
        device_class="temperature",
        unit="°C",
        writable=True,
        min_value=5,
        max_value=40,
        step=1,
        entity_type="number",
        entity_category="config",
    ),
    "ctlv2.Hc3SummerTempLimit": RegisterMeta(
        friendly_name="Summer Temp Limit (HC3)",
        device_class="temperature",
        unit="°C",
        writable=True,
        min_value=10,
        max_value=30,
        step=1,
        entity_type="number",
        entity_category="config",
    ),
    "ctlv2.Hc3MinCoolingTempDesired": RegisterMeta(
        friendly_name="Min Cooling Temp (HC3)",
        device_class="temperature",
        unit="°C",
        writable=True,
        min_value=5,
        max_value=30,
        step=1,
        entity_type="number",
        entity_category="config",
    ),
    "ctlv2.Hc3AutoOffMode": RegisterMeta(
        friendly_name="Auto Off Mode (HC3)",
        icon="mdi:thermostat-auto",
        writable=True,
        options=["eco", "comfort"],
        entity_type="select",
        entity_category="config",
    ),
    "ctlv2.Hc3PumpStatus": RegisterMeta(
        friendly_name="Pump Status (HC3)",
        entity_type="binary_sensor",
    ),
    "ctlv2.Hc3Status": RegisterMeta(
        friendly_name="Status (HC3)",
        entity_type="sensor",
        icon="mdi:information",
    ),
    "ctlv2.Hc3CircuitType": RegisterMeta(
        friendly_name="Circuit Type (HC3)",
        icon="mdi:information",
        entity_category="diagnostic",
    ),
    "ctlv2.Hc3ExcessTemp": RegisterMeta(
        friendly_name="Excess Temp (HC3)",
        device_class="temperature",
        unit="°C",
    ),
    "ctlv2.Hc3HeatCurveAdaption": RegisterMeta(
        friendly_name="Heat Curve Adaption (HC3)",
        icon="mdi:chart-bell-curve-cumulative",
    ),
    "ctlv2.Hc3RoomTempSwitchOn": RegisterMeta(
        friendly_name="Room Temp Threshold (HC3)",
        unit="°C",
    ),
    "ctlv2.Hc3MixerMovement": RegisterMeta(
        friendly_name="Mixer Movement (HC3)",
        icon="mdi:valve",
    ),
    # DHW
    "ctlv2.HwcTempDesired": RegisterMeta(
        friendly_name="DHW Target Temperature",
        device_class="temperature",
        unit="°C",
        writable=True,
        min_value=30,
        max_value=70,
        step=1,
        entity_type="number",
        entity_category="config",
    ),
    "ctlv2.HwcStorageTemp": RegisterMeta(
        friendly_name="DHW Storage Temperature",
        device_class="temperature",
        unit="°C",
    ),
    "ctlv2.HwcOpMode": RegisterMeta(
        friendly_name="DHW Operation Mode",
        writable=True,
        options=["off", "day", "night", "auto"],
        entity_type="select",
        entity_category="config",
    ),
    "ctlv2.HwcMaxFlowTempDesired": RegisterMeta(
        friendly_name="Max Flow Temperature (DHW)",
        device_class="temperature",
        unit="°C",
        writable=True,
        min_value=20,
        max_value=75,
        step=1,
        entity_type="number",
        entity_category="config",
    ),
    "ctlv2.HwcFlowTemp": RegisterMeta(
        friendly_name="DHW Flow Temperature",
        device_class="temperature",
        unit="°C",
    ),
    "ctlv2.HwcLockTime": RegisterMeta(
        friendly_name="DHW Lock Time",
        icon="mdi:clock-outline",
        unit="min",
        entity_category="config",
    ),
    "ctlv2.CylinderChargeHyst": RegisterMeta(
        friendly_name="Cylinder Charge Hysteresis",
        device_class="temperature",
        unit="°C",
        writable=True,
        min_value=1,
        max_value=20,
        step=1,
        entity_type="number",
        entity_category="config",
    ),
    "ctlv2.CylinderChargeOffset": RegisterMeta(
        friendly_name="Cylinder Charge Offset",
        device_class="temperature",
        unit="°C",
        writable=True,
        min_value=1,
        max_value=20,
        step=1,
        entity_type="number",
        entity_category="config",
    ),
    "ctlv2.HwcParallelLoading": RegisterMeta(
        friendly_name="DHW Parallel Loading",
        entity_type="binary_sensor",
        icon="mdi:water-boiler",
    ),
    "ctlv2.HwcSfMode": RegisterMeta(
        friendly_name="DHW SF Mode",
        icon="mdi:information",
    ),
    "ctlv2.HwcStorageTempBottom": RegisterMeta(
        friendly_name="DHW Storage Temp (Bottom)",
        device_class="temperature",
        unit="°C",
    ),
    "ctlv2.HwcStorageTempTop": RegisterMeta(
        friendly_name="DHW Storage Temp (Top)",
        device_class="temperature",
        unit="°C",
    ),
    "ctlv2.HwcHolidayStartPeriod": RegisterMeta(
        friendly_name="DHW Holiday Start",
        icon="mdi:calendar-start",
    ),
    "ctlv2.HwcHolidayEndPeriod": RegisterMeta(
        friendly_name="DHW Holiday End",
        icon="mdi:calendar-end",
    ),
    "ctlv2.HwcSFMode": RegisterMeta(
        friendly_name="DHW Special Function",
        icon="mdi:water-boiler",
    ),
    # Zones
    "ctlv2.DisplayedOutsideTemp": RegisterMeta(
        friendly_name="Displayed Outside Temp",
        device_class="temperature",
        unit="°C",
    ),
    "ctlv2.SystemFlowTemp": RegisterMeta(
        friendly_name="System Flow Temperature",
        device_class="temperature",
        unit="°C",
    ),
    "ctlv2.WaterPressure": RegisterMeta(
        friendly_name="Water Pressure",
        device_class="pressure",
        unit="bar",
    ),
    "ctlv2.Currenterror": RegisterMeta(
        friendly_name="Error",
        icon="mdi:alert",
        entity_category="diagnostic",
    ),
    "ctlv2.AdaptHeatCurve": RegisterMeta(
        friendly_name="Adapt Heat Curve",
        writable=True,
        options=["no", "yes"],
        entity_type="select",
        entity_category="config",
    ),
    "ctlv2.ContinuousHeating": RegisterMeta(
        friendly_name="Continuous Heating",
        icon="mdi:radiator",
        entity_category="diagnostic",
    ),
    "ctlv2.HcStorageTempBottom": RegisterMeta(
        friendly_name="Heating Storage Temp (Bottom)",
        device_class="temperature",
        unit="°C",
        enabled=False,
    ),
    "ctlv2.HcStorageTempTop": RegisterMeta(
        friendly_name="Heating Storage Temp (Top)",
        device_class="temperature",
        unit="°C",
        enabled=False,
    ),
    "ctlv2.HydraulicScheme": RegisterMeta(
        friendly_name="Hydraulic Scheme",
        icon="mdi:pipe-valve",
        entity_category="diagnostic",
    ),
    "ctlv2.MaxCylinderChargeTime": RegisterMeta(
        friendly_name="Maximum Cylinder Charge Time",
        icon="mdi:timer-outline",
        unit="min",
        entity_category="diagnostic",
    ),
    "ctlv2.MultiRelaySetting": RegisterMeta(
        friendly_name="Multi Relay Setting",
        icon="mdi:relay",
        entity_category="diagnostic",
    ),
    "ctlv2.OutsideTempAvg": RegisterMeta(
        friendly_name="Average Outside Temperature",
        device_class="temperature",
        unit="°C",
    ),
    "ctlv2.Z1CoolingTemp": RegisterMeta(
        friendly_name="Zone Cooling Temperature",
        device_class="temperature",
        unit="°C",
    ),
    "ctlv2.Z1HolidayStartPeriod": RegisterMeta(
        friendly_name="Holiday Start",
        icon="mdi:calendar-start",
    ),
    "ctlv2.Z1HolidayEndPeriod": RegisterMeta(
        friendly_name="Holiday End",
        icon="mdi:calendar-end",
    ),
    "ctlv2.Z1QuickVetoEndDate": RegisterMeta(
        friendly_name="Quick Veto End Date",
        icon="mdi:calendar-clock",
    ),
    "ctlv2.Z1QuickVetoEndTime": RegisterMeta(
        friendly_name="Quick Veto End Time",
        icon="mdi:clock-outline",
    ),
    "ctlv2.Z1RoomTemp": RegisterMeta(
        friendly_name="Room Temperature",
        device_class="temperature",
        unit="°C",
    ),
    "ctlv2.Z1QuickVetoDuration": RegisterMeta(
        friendly_name="Quick Veto Duration",
        icon="mdi:timer-outline",
        writable=True,
        min_value=0,
        max_value=24,
        step=1,
        entity_type="number",
        entity_category="config",
    ),
    "ctlv2.Z1QuickVetoTemp": RegisterMeta(
        friendly_name="Quick Veto Temperature",
        device_class="temperature",
        unit="°C",
        writable=True,
        min_value=5,
        max_value=30,
        step=0.5,
        entity_type="number",
        entity_category="config",
    ),
    "ctlv2.Z1HolidayTemp": RegisterMeta(
        friendly_name="Holiday Temperature",
        device_class="temperature",
        unit="°C",
        writable=True,
        min_value=5,
        max_value=30,
        step=0.5,
        entity_type="number",
        entity_category="config",
    ),
    "ctlv2.Z1SFMode": RegisterMeta(
        friendly_name="Zone Special Function",
        icon="mdi:home-thermometer",
        entity_category="diagnostic",
    ),
    "ctlv2.MaxRoomHumidity": RegisterMeta(
        friendly_name="Max Room Humidity",
        icon="mdi:water-percent",
        unit="%",
        writable=True,
        min_value=0,
        max_value=100,
        step=1,
        entity_type="number",
        entity_category="config",
    ),
    "ctlv2.z1RoomHumidity": RegisterMeta(
        friendly_name="Room Humidity",
        device_class="humidity",
        unit="%",
        icon="mdi:water-percent",
    ),
    "ctlv2.Date": RegisterMeta(
        friendly_name="Date",
        icon="mdi:calendar",
        entity_category="diagnostic",
    ),
    "ctlv2.FrostOverRideTime": RegisterMeta(
        friendly_name="Frost Override Time",
        icon="mdi:snowflake",
        entity_category="diagnostic",
    ),
    "ctlv2.Errorhistory": RegisterMeta(
        friendly_name="Error History",
        icon="mdi:alert-circle-outline",
        entity_category="diagnostic",
    ),
    # cctimer (Schedule) — mark as diagnostic for now
    "ctlv2.CcTimer_Config": RegisterMeta(
        friendly_name="Schedule Config",
        icon="mdi:calendar-clock",
        entity_category="diagnostic",
    ),
    "ctlv2.CcTimer_Timeframes": RegisterMeta(
        friendly_name="Schedule Timeframes",
        icon="mdi:calendar-clock",
        entity_category="diagnostic",
    ),
    # Broadcast (System)
    "Broadcast.Outsidetemp": RegisterMeta(
        friendly_name="Outside Temperature",
        device_class="temperature",
        unit="°C",
    ),
    "Broadcast.Vdatetime": RegisterMeta(
        friendly_name="Date/Time",
        icon="mdi:clock",
        entity_category="diagnostic",
    ),
    "Broadcast.Datetime": RegisterMeta(
        friendly_name="Date/Time (alt)",
        icon="mdi:clock",
        entity_category="diagnostic",
    ),
    "Broadcast.Error": RegisterMeta(
        friendly_name="System Error",
        icon="mdi:alert",
        entity_category="diagnostic",
    ),
    "Broadcast.HwcStatus": RegisterMeta(
        friendly_name="DHW Status",
        entity_type="binary_sensor",
        entity_category="diagnostic",
    ),
    "Broadcast.WaterPressure": RegisterMeta(
        friendly_name="Water Pressure",
        device_class="pressure",
        unit="bar",
    ),
    "Broadcast.FlowTemp": RegisterMeta(
        friendly_name="Flow Temperature",
        device_class="temperature",
        unit="°C",
    ),
    # vwz (Valve) — test registers, disabled
    "vwz.TestHwcTemp": RegisterMeta(
        friendly_name="DHW Temperature (test)",
        device_class="temperature",
        unit="°C",
        entity_category="diagnostic",
        enabled=False,
    ),
    "vwz.TestOutdoorTemp": RegisterMeta(
        friendly_name="Outdoor Temperature (test)",
        device_class="temperature",
        unit="°C",
        entity_category="diagnostic",
        enabled=False,
    ),
    "vwz.TestThreeWayValve": RegisterMeta(
        friendly_name="Three-Way Valve (test)",
        entity_category="diagnostic",
        enabled=False,
    ),
}


def get_meta(circuit: str, name: str, field: str = "value") -> RegisterMeta:
    key = f"{circuit}.{name}"
    if field != "value":
        key += f".{field}"
    return REGISTER_MAP.get(key, RegisterMeta())
